services:
  pgdatabase:
    image: postgres:13.13-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=ny_taxi
    volumes:
      - "C:/Users/jeff/OneDrive/Documents/Projects/Learning/ZoomCamp2024/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    
